spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
# Hikari Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# Security
api.key=${API_KEY}
jwt.secret=${JWT_SECRET}

# Permitir cargas pesadas (hasta 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=50MB

# Hibernate Batching
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Producción: Seguridad de Errores y Excepciones
server.error.include-exception=false
server.error.include-stacktrace=never
server.error.include-message=always

# Automatización de Carga de Inventario
app.auto-import.input-path=${RUTA_DESCARGA:app/downloads}
app.auto-import.processed-path=${RUTA_PROCESADOS:app/downloads/procesados}
app.auto-import.enabled=${APP_AUTO_IMPORT_ENABLED}
app.auto-import.delete-after-process=${APP_AUTO_IMPORT_DELETE_AFTER_SUCCESS}

# Configuración del SFTP
app.sftp.host=${SFTP_HOST}
app.sftp.username=${SFTP_USER}
app.sftp.password=${SFTP_PASSWORD}
app.sftp.port=${SFTP_PORT}
app.sftp.remote-path=${SFTP_REMOTE_PATH}

# Health Check (Actuator)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
