spring.application.name=backend_CONTEOCICLICO
spring.datasource.url=jdbc:mysql://10.0.1.115:3306/conteociclico?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true
spring.datasource.username=admin
spring.datasource.password=Adm1n*.2024/
spring.jpa.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect



# Security
api.key=pharmaser_secure_api_key_2026

# Permitir cargas pesadas (hasta 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=50MB

# Hibernate Batching
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Producción: Seguridad de Errores y Excepciones
server.error.include-exception=false
server.error.include-stacktrace=never
server.error.include-message=always
